{
 "title": "dotnet-game-api-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RAW LOG",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"dotnet-game-api\"} != `metrics`"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{namespace=\"dotnet-game-api\"} |= `error` |~ \"404|500\""
    }
   ]
  },
  {
   "title": "500 Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate({namespace=\"dotnet-game-api\"} |~ \"5(01|02|03|04|05|06|07|08|09|10|12|13|14|15|16|17|18|19|2[0-9]|3[0-9]|4[0-9]|5[0-9]|6[0-9]|7[0-9]|8[0-9]|9[0-9])|status=5[0-9]{2}\" [$__auto]))\r\n"
    }
   ]
  },
  {
   "title": "4XX Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate({namespace=\"dotnet-game-api\"} |~ \"4(01|02|03|04|05|06|07|08|09|10|12|13|14|15|16|17|18|19|2[0-9]|3[0-9]|4[0-9]|5[0-9]|6[0-9]|7[0-9]|8[0-9]|9[0-9])|status=5[0-9]{2}\" [$__auto]))\r\n"
    }
   ]
  },
  {
   "title": "Queries Made",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "player_requests_total{namespace=\"dotnet-game-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Player quries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(player_requests_total{namespace=\"dotnet-game-api\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}