global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'method']  # Group alerts by alert name and method
  group_wait: 30s                   # Wait 30 seconds before sending the first notification
  group_interval: 5m                # After the first notification, wait 5 minutes before sending another for the same group
  repeat_interval: 1h               # Send repeated notifications every hour
  receiver: "email-notifications"   # Default receiver for all alerts

receivers:
  - name: "slack-notifications"
    slack_configs:
      - channel: "#alerts"
        send_resolved: true
        api_url: 'https://hooks.slack.com/services/...'

  - name: "email-notifications"
    email_configs:
      - to: 'ops-team@example.com'
        from: 'prometheus-alerts@example.com'
        send_resolved: true
        smarthost: 'smtp.example.com:587'
        auth_username: 'your-email@example.com'
        auth_password: 'your-email-password'

# Optional: Silence configurations to suppress certain alerts during maintenance
silences:
  - matchers:
      - name: alertname
        value: "HighErrorRate"
    start: "2024-12-28T00:00:00Z"
    end: "2024-12-28T06:00:00Z"
    created_by: "admin"
    comment: "Silence during scheduled maintenance"
