# Example custom values.yaml for kube-prometheus-stack
prometheus:
  service:
    type: LoadBalancer
  enabled: true
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
  replicas: 1
  namespace: monitoring
  serviceMonitorSelector: {} #match all svc monitors
  podMonitorSelector: {} #match all pod monitors
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

grafana:
  service:
    enabled: true
    type: LoadBalancer
  enabled: true
  adminPassword: "admin"  # Set your desired password here
  additionalDatasources:
    - name: Loki
      type: loki
      url:  http://loki.logging.svc.cluster.local:3100
      access: proxy
      isDefault: true 


alertmanager:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
  alertmanagerSpec:
    replicas: 1


kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false