  promtail:
    enabled: true
    config:
      logLevel: info
      serverPort: 3101
      clients:
        - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
      scrape_configs:
        - job_name: kubernetes-pods
          pipeline_stages:
            - docker: {}
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                names:
                  - gman-go-server
          relabel_configs:
            - action: replace
              source_labels: [__meta_kubernetes_namespace]
              target_label: kubernetes_namespace
            - action: replace
              source_labels: [__meta_kubernetes_pod_name]
              target_label: kubernetes_pod_name
