# values.yaml

# Default values for gman-go-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: shreyasgune/gman-go-server
  tag: 0.0.3
  pullPolicy: IfNotPresent

service:
  name: gman-go-server
  type: ClusterIP
  port: 2112
  targetPort: 2112

ingress:
  enabled: false
  annotations: {}
  path: /
  host: gman-go-server.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: "ENV_VAR_1"
    value: "value1"
  - name: "ENV_VAR_2"
    value: "value2"

livenessProbe:
  httpGet:
    path: /metrics
    port: 2112
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /metrics
    port: 2112
  initialDelaySeconds: 5
  periodSeconds: 5

promScrape:
  scrape: "true"
  path: "/metrics"
  port: "2112"

podMon: false
svcMon: false