version: '3'

services:
  fastapi-app:
    image: shreyasgune/fastapi
    # build:
    #   context: app/
    #   dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - monitoring
    environment:
      - PYTHONBUFFERED=1

  prometheus:
    image: prom/prometheus:v2.37.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:9.0.0
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring: